/*
 * This file was generated by the Gradle 'init' task.
 * Triggering IDE sync.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    alias(libs.plugins.ktor)
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(libs.logback.classic)
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.netty)
    implementation(libs.ktor.server.status.pages)
    implementation(libs.ktor.server.config.yaml)
    implementation(libs.ktor.server.test.host)
    implementation(libs.kotlin.test.junit)
    implementation(libs.arrow.core)
    implementation(project(":lib"))
}

application {
    mainClass = "com.kanuhead.endpointspec.ApplicationKt"
}
